import type { Metadata } from "next";
import { Poppins, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import BackgroundWrapper from "./BackgroundWrapper";

const raleway = Raleway({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Home - Creativebase8",
    template: "%s - Creativebase8",
  },
  description: "Generated by create next app",
};

// random background
const bgNumber = Math.floor(Math.random() * 21) + 1;
const backgroundImage = `/assets/background${bgNumber}.webp`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased`}>
        <BackgroundWrapper>
          <Navbar />
          {children}
          <Footer />
        </BackgroundWrapper>
      </body>
    </html>
  );
}
